### ISSUE TITLE
Second call to getJobs causes jobs to be instantiated twice.

### ISSUE THREAD

**Issue by edovale** [dropwizard-jobs/dropwizard-jobs#123]
Is it really necessary to make this call here again? The call to the super constructor already locates all the jobs in the guice context; why call it again?

https://github.com/dropwizard-jobs/dropwizard-jobs/blob/82749ca5ab8940bb87691273038b78b3d2a17cda/dropwizard-jobs-guice/src/main/java/io/dropwizard/jobs/GuiceJobManager.java#L23

**Comment by hakandilek** [comment]
Good catch @edovale .

Would you like to provide a patch before the release?

**Comment by edovale** [comment]
Will do.

**Comment by grommitz** [comment]
merged the PR, thanks Erick

**Comment by edovale** [comment]
awesome. Thank you.
