### ISSUE TITLE
Failure to find io.github.dropwizard-jobs:dropwizard-jobs:jar:4.0.0-RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

### ISSUE THREAD

**Issue by Lavie526** [dropwizard-jobs/dropwizard-jobs#127]
I have added  the below dependency settings in the pom

<dependency>
  <groupId>io.github.dropwizard-jobs</groupId>
  <artifactId>dropwizard-jobs</artifactId>
  <version>4.0.0-RELEASE</version>
</dependency>

Howwever, i am still meet the build error? anything wrong?

**Comment by Lavie526** [comment]
I also tried to build in local, the latest version is 4.1.0-SNAPSHOT, but it won't be pull from local.

**Comment by christopherkao** [comment]
I found that I needed to use `dropwizard-jobs-core` instead of `dropwizard-jobs`. See here: https://mvnrepository.com/artifact/io.github.dropwizard-jobs/dropwizard-jobs-core

**Comment by hakandilek** [comment]
> I found that I needed to use `dropwizard-jobs-core` instead of `dropwizard-jobs`. See here: https://mvnrepository.com/artifact/io.github.dropwizard-jobs/dropwizard-jobs-core

Updated README to prevent this confusion.
