### ISSUE TITLE
Is there a way to trigger a job manually?

### ISSUE THREAD

**Issue by gnoorinvidi** [dropwizard-jobs/dropwizard-jobs#152]
I'm trying to add support for triggering jobs manually via an endpoint. Is this possible via dropwizard jobs, or perhaps via the underlying Quartz scheduler library? Please let me know

**Comment by hakandilek** [comment]
well you can do that using Quartz. You might need a reference to the corresponding `Job` instance.

Please google or GPT it. I'm closing this issue since it's not much relevant.

**Comment by gnoorinvidi** [comment]
@hakandilek  I tried getting the instance of the scheduler using `StdSchedulerFactory.getDefaultScheduler()`. When I try to call `getJobGroupNames()` on the scheduler, I get back an empty list. I'm really confused because we have scheduled jobs, and they run as expected. Could it be that the `getDefaultScheduler()` function is returning a different instance of the scheduler than the one used in the dropwizard jobs library?
