### ISSUE TITLE
Missing 5.0.0 release in maven central 

### ISSUE THREAD

**Issue by mustafashabib** [dropwizard-jobs/dropwizard-jobs#168]
Are there plans to publish the latest release to maven ? 

https://mvnrepository.com/artifact/io.github.dropwizard-jobs/dropwizard-jobs  doesn't yet list it, though the [Readme](https://github.com/dropwizard-jobs/dropwizard-jobs#using-maven-central-repository) says to use it.

**Comment by hakandilek** [comment]
There's been a problem with the 5.0.0 release. You can use the snapshot releases here: https://github.com/orgs/dropwizard-jobs/packages?repo_name=dropwizard-jobs until it's fixed.

**Comment by hakandilek** [comment]
Solved the issue.

You can access v5.0.1 over maven now:
https://central.sonatype.com/artifact/io.github.dropwizard-jobs/dropwizard-jobs/5.0.1/overview

Closing this issue.

**Comment by mustafashabib** [comment]
Thank you
