### ISSUE TITLE
JobConfiguration is a class, but docs still treat it as an interface

### ISSUE THREAD

**Issue by Zinurist** [dropwizard-jobs/dropwizard-jobs#192]
I'm referring to this in the Readme:
```
public class ApplicationConfiguration extends Configuration implements JobConfiguration
```
I recently updated this library, and I guess you just extend JobConfiguration now instead?

**Comment by hakandilek** [comment]
Thanks for pointing this out @Zinurist. I've obviously missed this one after updating for the new release.

Would you care to fix it and propose a PR?

**Comment by Zinurist** [comment]
I don't really intend to open a PR, it's probably easier/faster if you do it.

**Comment by hakandilek** [comment]
That's fine. I was on vacation and thought you might do it faster. Created #193 to update the README. I suppose that's ok.
