### ISSUE TITLE
Make multiple contributors can be deployed

### ISSUE THREAD

**Issue by t-tsutsumi** [dropwizard-jobs/dropwizard-jobs#56]
This issue shares progress on this subject and to allow discussions. See also #49.

IMHO, the following tasks are required.
- [x] Create a new GitHub organization such as `dropwizard-jobs`.
- [x] Add the trusted contributors to members of the organization.
- [x] Transfer ownership of `spinscale/dropwizard-jobs` to the organization.
- [x] Revise the `pom.xml`. (groupId, scm...)
- [x] Create a [new project ticket](https://issues.sonatype.org/browse/OSSRH-39526) with Sonatype
    * Assign the new Maven `groupId` such as `io.github.dropwizard-jobs`. Note: The privilege to operate the Sonatype repository is assigned per `groupId`.
    * Add the trusted contributors to members of the `groupId` via the ticket, this can be done later.

... (Same as general Maven project.)

- [x] Migrate the build configuration of Travis CI. 
- [ ] Deploy directly in Travis CI as [done by Dropwizard](https://github.com/dropwizard/dropwizard/blob/master/.travis_deploy.sh)
- [ ] Add to [Dropwizard Modules Directory](http://modules.dropwizard.io/thirdparty/). (Optional)

@spinscale @xargsgrep I would like to get your thoughts on that.

**Comment by spinscale** [comment]
I am happy with whatever helps the community, I just dont have any time to do that myself - with the exception of transferring ownership when everything is in place.

**Comment by t-tsutsumi** [comment]
@spinscale Thanks for your reply. I myself can do this work to maintain dropwizard-jobs project, but I would like to wait for about a month to see if there are other people who intend to take over the project.

**Comment by MusikPolice** [comment]
This is an excellent idea. I merged a few pull requests today, but don't have the ability to release a new version.

**Comment by hakandilek** [comment]
There's some pressure to move on with this plan(see #73), so I'm giving this one a go.

**Comment by hakandilek** [comment]
I did create the organization and invited the official contributors listed in the `README.md`. Tell if I'm missing someone.

@spinscale could you please transfer the ownership if everything looks ok?

**Comment by hakandilek** [comment]
After some thinking, why don't we (auto)deploy directly with travis-ci?
There are some how-tos:

- http://www.debonair.io/post/maven-cd/
- https://gist.github.com/letmaik/4060735
- https://github.com/JakeWharton/butterknife/commit/bac2342500971a3c6664629c3a63ca74d6e4819c

**Comment by spinscale** [comment]
@hakandilek done

**Comment by hakandilek** [comment]
Thanks @spinscale !
I did wait a couple of days for other contributors to join the new organization but nobody else joined yet. 
Meanwhile we can discuss if we need another major version bump since groupIds `pom.xml` will change.

**Comment by spinscale** [comment]
+1 for major release on such a big change

**Comment by spinscale** [comment]
I also think you may need to invite the others specifically (not sure how all of this works, but making it explicit makes sense I guess)

**Comment by hakandilek** [comment]
Yes I did invite everyone in the contributors list.

**Comment by hakandilek** [comment]
What about packages?
Does it make sense for a rename like `de.spinscale.dropwizard.jobs` -> `io.dropwizard.jobs`?

**Comment by hakandilek** [comment]
First snapshot uploaded to: https://oss.sonatype.org/content/repositories/snapshots/io/github/dropwizard-jobs/dropwizard-jobs/

**Comment by hakandilek** [comment]
listed as 3rd-party module: https://github.com/dropwizard/modules.dropwizard.io/pull/87
