### ISSUE TITLE
Bootstrap.addBundle  incompatible with  JobsBundle

### ISSUE THREAD

**Issue by aschermann** [dropwizard-jobs/dropwizard-jobs#61]
bootstrap.addBundle need Bundle or ConfiguredBundle<? super T> .
![2017-08-16_121328](https://user-images.githubusercontent.com/10641152/29358852-dd0b6f42-827c-11e7-80ac-4d7bd2836312.jpg)

**Comment by eonwhite** [comment]
You need to have your `DissertationProcessMicroserviceConfiguration` class implement `JobConfiguration` (see #48)

This stumped me also until I went browsing the issues -- I just submitted a PR to help clarify initial setup instructions.

**Comment by hakandilek** [comment]
Closing this one as clarified by @eonwhite a while ago.
