### ISSUE TITLE
Release dropwizard-jobs v2.1.0

### ISSUE THREAD

**Issue by MusikPolice** [dropwizard-jobs/dropwizard-jobs#63]
We've recently received and accepted a PR that upgrades the version of Dropwizard that the project uses. This should qualify as a backward-compatible point release, but I don't know how to do the release.

**Comment by derkd** [comment]
Is it possible to release 3.0.1 with the latest pr's in it?

**Comment by spinscale** [comment]
I gave it a quick go, but the GPG signing with mvn3 seems broken... I cant provide a passphrase (and I wont type it in several dozen times), must be sth on my side but I havent found whats the cause yet

**Comment by derkd** [comment]
@spinscale have you tried it with this
`mvn verify -Dgpg.passphrase=thephrase` command?

**Comment by MusikPolice** [comment]
@spinscale any update on getting a release out? I'd really like to improve this process so that we aren't always nagging you to do it.

**Comment by karlgrund** [comment]
What's the progress here? I'm also looking forward to the latest version.

**Comment by MusikPolice** [comment]
To the best of my knowledge, @spinscale is the only person with the ability to cut releases. If I'm wrong, and somebody in the community can do it, we may be able to get this task unblocked.

**Comment by spinscale** [comment]
if someone fixes the GPG signing issues, that require entering the passphrase for every artifact, I am happy to deploy. My maven skills recede quickly thanks to gradle...

Also, if you want to move the whole repo into its own github org and deploy that to sonatype, please go ahead, I am happy to move the repo where ever it should be moved.

**Comment by izrobin** [comment]
@spinscale 
I guess you can add 
`<passphrase>${gpg.passphrase}</passphrase>`
to the plugin configuration, and provide the passphrase on command line when releasing.
`-Dgpg.passphrase=myverysupersecretpassphrase`

That's one way I can think of. I'm not sure if the plugin supports using the OSX Keychain access or something similar

**Comment by eonwhite** [comment]
It's too bad that this project is having challenges cutting releases as I've found it quite useful for scheduling crons.

Due to the issues surrounding this project, and some unrelated Quartz problems I've had, I've been moving my projects away from the use of dropwizard-jobs and Quartz generally, and towards a simpler approach using a distributed worker consuming events off SQS, with crons triggered by CloudWatch. I've open sourced the code here if anyone is interested: https://github.com/stardogventures/dropwizard-worker (you have to be on AWS to make use of it currently)

**Comment by oliver-steinbrecher** [comment]
Any updates reading a proper released version 3.0.1 . We would really like to use this library ...

**Comment by izrobin** [comment]
@eonwhite I've made an attempt to write my open source dropwizard-quartz integration.
It doesn't support clustered quartz for instance, any DB persistence, or job configuration via yaml.
But it's very lighweight and solves our use cases at least.

Feel free to check it out, test around and contribute. It's still a work in progress.
https://github.com/izrobin/dropwizard-quartz

**Comment by hakandilek** [comment]
I have changed the groupId, package names and released a 4.0.0-SNAPSHOT version couple of minutes ago: https://oss.sonatype.org/content/repositories/snapshots/io/github/dropwizard-jobs/dropwizard-jobs/4.0.0-SNAPSHOT/

As this is a major change, we decided to skip any 3.x versions and jump to 4.x. You have to adapt the package imports and `pom.xml`s but it will bring a major advantage of automated releases. 

From now on all changes on the master will be reflected immediately on Sonatype as SNAPSHOT releases through the Travis-CI.
