### ISSUE TITLE
Deploy the 3.0.1 Release?

### ISSUE THREAD

**Issue by gna-phetsarath** [dropwizard-jobs/dropwizard-jobs#73]
Hi there!  I really like this Bundle and would like to use it with my code but...I need the latest features in the `master` branch. 

Would it be possible for you to cut a 3.0.1 release and deploy to Maven Central?

Thanks!

**Comment by ohallors** [comment]
We also need the features in 3.0.1, any chance of getting a release soon to Maven Central? Pretty please :-)

**Comment by hakandilek** [comment]
I'd like to but can't do it at the moment. Only @spinscale has the credentials and he usually does not have the time to do it immediately for every release. We have a solution for that though: #56 

We had the same problem before deploying 3.0.0: #49

**Comment by hakandilek** [comment]
I'm closing this as we've deployed 4.0.0-SNAPSHOT. see #87 and #56
