### ISSUE TITLE
Dropwizard YAML job configuration with @On

### ISSUE THREAD

**Issue by migzai** [dropwizard-jobs/dropwizard-jobs#79]
Hi,

I've defined one job in my YAML configuration file:

jobs:
  cronJob: "0 0/3 0 ? * * *"

Now in my job class, i'm trying to use it:

@On("${cronJob}")
public class DbCleanupJob extends Job

I'm getting the below exception:

! java.text.ParseException: Unexpected character: $
! at org.quartz.CronExpression.storeExpressionVals(CronExpression.java:707)
! at org.quartz.CronExpression.buildExpression(CronExpression.java:487)
! at org.quartz.CronExpression.<init>(CronExpression.java:276)
! at org.quartz.CronScheduleBuilder.cronSchedule(CronScheduleBuilder.java:107)
! ... 17 common frames omitted
! Causing: java.lang.RuntimeException: CronExpression '${cronJob}' is invalid.
! at org.quartz.CronScheduleBuilder.cronSchedule(CronScheduleBuilder.java:111)
! at de.spinscale.dropwizard.jobs.JobManager.scheduleAllJobsWithOnAnnotation(JobManager.java:112)
! at de.spinscale.dropwizard.jobs.JobManager.scheduleAllJobs(JobManager.java:79)
! at de.spinscale.dropwizard.jobs.JobManager.start(JobManager.java:53)
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
! at org.eclipse.jetty.server.Server.start(Server.java:418)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.server.Server.doStart(Server.java:385)
! ... 7 common frames omitted
! Causing: org.eclipse.jetty.util.MultiException: Multiple exceptions
! at org.eclipse.jetty.server.Server.doStart(Server.java:382)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at com.l0g1c.gotlunch.server.GotLunchServer.main(GotLunchServer.java:75)
! Suppressed: java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.io.ManagedSelector$$Lambda$125/79406632@247added
! 	at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:402)
! 	at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:171)
! 	at org.eclipse.jetty.io.ManagedSelector.doStart(ManagedSelector.java:101)
! 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
! 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
! 	at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:271)
! 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
! 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
! 	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:278)
! 	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
! 	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:238)
! 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! 	at org.eclipse.jetty.server.Server.doStart(Server.java:397)
! 	... 7 common frames omitted
! Suppressed: java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.io.ManagedSelector$$Lambda$125/79406632@50dfceff
! 	at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:402)
! 	at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:171)
! 	at org.eclipse.jetty.io.ManagedSelector.doStart(ManagedSelector.java:101)
! 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
! 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
! 	at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:271)
! 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
! 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
! 	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:278)
! 	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
! 	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:238)
! 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! 	at org.eclipse.jetty.server.Server.doStart(Server.java:397)
! 	... 7 common frames omitted

**Comment by grommitz** [comment]
should work... I've added a test case (see PR #80). can you double check things like the indentation in the yml file and there are extraneous spaces inside the annotation value etc

**Comment by hakandilek** [comment]
@migzai can you please confirm that it's working with the SNAPSHOT?

**Comment by migzai** [comment]
Yes it does.

**Comment by hakandilek** [comment]
Thanks. I'm closing this one.
