### ISSUE TITLE
Artifact not found in maven central

### ISSUE THREAD

**Issue by vic0075** [dropwizard-jobs/dropwizard-jobs#81]
There only two artifacts with the name `dropwizard-jobs-core`

de.spinscale.dropwizard | dropwizard-jobs-core | 3.0.0  all (2) | 08-Feb-2017

de.spinscale | dropwizard-jobs-core | 1.1.5  all (4) | 03-Nov-2016

No artifact with group - "dropwizard-jobs"

**Comment by grommitz** [comment]
That's right, the groupId dropwizard-jobs will be used from version 4.0.0 onwards.

**Comment by KatseNarniaan** [comment]
Any idea when version 4.0.0 will be on maven central?

**Comment by hakandilek** [comment]
@vic0075 and @KatseNarniaan could one of you please test and confirm the 4.0.0-SNAPSHOT release?

https://oss.sonatype.org/content/repositories/snapshots/io/github/dropwizard-jobs/dropwizard-jobs/4.0.0-SNAPSHOT/

**Comment by KatseNarniaan** [comment]
Works for me. Thanks!

**Comment by adamrmelnyk** [comment]
Any Idea when this will be available? I don't see the snapshots of 4.0.0 in the maven central repository. Until then the docs are misleading.

**Comment by jonevn** [comment]
Any new information on possible release date?

**Comment by alexey-krylov** [comment]
@hakandilek @grommitz any plans to release 4.0.0 version? We going to prod soon, it's bad idea to depend on snapshot versions :(

**Comment by jansoren** [comment]
What is the holdup on this? And could you create a release candidate?

**Comment by hakandilek** [comment]
It's mainly contributors' lack of time.

I personally want to build a sustainable release mechanism integrating maven and travisci with sonatype. Unfortunately I couldn't find the time to read Sonatype guidelines and come up with a nice solution. If someone is interested, I can support you guy.

**Comment by hakandilek** [comment]
I've finally managed to clean some vulnerable dependencies and  setup the travis pipeline for push a RC.
Could you please give it a go for the `4.0.0-RC1` version?

@alexey-krylov @jansoren?

**Comment by alexey-krylov** [comment]
@hakandilek thank you so much! Yes, 4.0.0-RC1 appeared in Maven Central

**Comment by hakandilek** [comment]
Closing this, as 4.0.0 is released
